#!/usr/bin/env python3
"""Generate the site's attribution page from the repository's own registries.

Licensing is the one real compliance surface on this project, so this page is
**computed, never hand-written**.  It enumerates every dataset card in
``scwbd/sources/cards/`` and every anatomy source in ``scwbd/anatomy/sources.py``,
renders them through ``scwbd.sources.attribution``, and unions their terms
through ``scwbd.release.licence``.

Hand-typing a source list here would reintroduce exactly the defect the
attribution module exists to prevent — a citation set that is a memory of what
we used rather than a record of it.

Writes ``site/content/attribution.html``.  Run before ``site/build.py``.
"""

from __future__ import annotations

import html
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
sys.path.insert(0, str(REPO))

from scwbd.anatomy.sources import SRC  # noqa: E402
from scwbd.release.licence import term_from_dataset_card, term_from_licence_text, union_of  # noqa: E402
from scwbd.release.manifest import DOWNSTREAM_REACH_QUESTION, OWNER_LICENCE_DECISION  # noqa: E402
from scwbd.sources.attribution import (  # noqa: E402
    attribution_for_anatomy,
    attribution_for_datasets,
)

CARD_DIR = REPO / "scwbd" / "sources" / "cards"
OUT = ROOT / "content" / "attribution.html"


def e(s: object) -> str:
    return html.escape(str(s))


def entry_rows(block, kind_label: str) -> str:
    rows = []
    for a in block.entries:
        links = []
        if a.doi:
            links.append(f'<a href="https://doi.org/{e(a.doi)}">doi:{e(a.doi)}</a>')
        if a.url:
            links.append(f'<a href="{e(a.url)}">source</a>')
        link_html = " · ".join(links)
        rows.append(
            "<tr>"
            f'<td><code>{e(a.key)}</code></td>'
            f"<td>{e(a.citation)}</td>"
            f"<td>{e(a.licence)}{'<br>' + link_html if link_html else ''}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def main() -> None:
    dataset_ids = sorted(p.stem for p in CARD_DIR.glob("*.yaml"))
    anatomy_keys = sorted(SRC.keys())

    ds_block = attribution_for_datasets(dataset_ids, card_dir=CARD_DIR)
    an_block = attribution_for_anatomy(anatomy_keys)

    # `--text` prints the citation set instead of writing the page, so the same
    # enumeration backs both `make attribution` and the published page. Two code
    # paths producing two source lists is exactly the drift this module exists
    # to prevent.
    if "--text" in sys.argv:
        print(ds_block.require_complete().render())
        print()
        print(an_block.require_complete().render())
        return

    terms = []
    for did in dataset_ids:
        try:
            terms.append(term_from_dataset_card(CARD_DIR / f"{did}.yaml"))
        except Exception:  # a card without governance still counts as unknown
            pass
    for key in anatomy_keys:
        meta = SRC[key]
        lic = meta.get("licence") or meta.get("license")
        terms.append(
            term_from_licence_text(
                key,
                lic,
                provenance=f"scwbd/anatomy/sources.py::SRC[{key!r}]",
                verified=False,
                url=meta.get("url"),
            )
        )

    union = union_of(terms)
    summary = union.summary()

    unattributable = list(ds_block.unattributable) + list(an_block.unattributable)

    parts: list[str] = []
    parts.append(f"""title: Attribution and licensing — SC-WBD
description: The computed citation set and licence union for every data source SC-WBD holds.
nav: attribution
kicker: Compliance
heading: Attribution and licensing
standfirst: This page is generated from the repository's own source registries, not written by hand. Every citation below is a licence condition, not a courtesy.
---
<div class="prose">

<p class="lede">SC-WBD is built on publicly released atlases, receptor maps and
neuroimaging datasets. Several of them attach conditions — attribution,
non-commercial use, share-alike — and those conditions propagate into anything
derived from them.[[note: Generated by <code>site/gen_attribution.py</code>, which
enumerates every card in <code>scwbd/sources/cards/</code> and every entry in
<code>scwbd/anatomy/sources.py</code> and renders them through the same
<code>scwbd.sources.attribution</code> module the release path uses. Regenerate
with <code>make site-attribution</code>.]]</p>

<div class="callout">
<span class="callout-label">Computed, not declared</span>
<p>Licence is <strong>computed</strong> from the source registries and split into
<em>inheritance</em> (what the sources impose) and <em>policy</em> (what the owner
chose). The two are never summed into a single boolean, because only the second
is the owner's to revoke.[[src: scwbd/release/licence.py]]</p>
</div>

<h2>Effective licence union</h2>

<p>The union below is the <strong>worst case over every source the repository
holds</strong>, including sources no default code path currently loads. It is not
a statement about any particular artifact.</p>

<pre><code>{e(summary)}</code></pre>

<p>Read the trailing clause literally: <strong>unknown is not permissive.</strong>
A source whose licence text names no terms is carried as unresolved, never
rounded down to “fine”.[[note: <code>is_vacuous_licence_text</code> exists because a
registry entry once read “See repository LICENSE (open, academic use)” for an
atlas whose actual licence imposes no academic-use limit at all — an invented
restriction, since corrected. The classifier now refuses to resolve text that
names no terms.]]</p>

<h2>The three conditions that bind</h2>

<h3>Hansen receptor maps — CC-BY-NC-SA-4.0</h3>
<p>Non-commercial <em>and</em> share-alike. Two questions have to be kept apart,
and a page that merges them will misreport: <strong>does the object contain
Hansen data</strong>, and <strong>does the default prior read it</strong>? These
have different answers today.[[src: reports/licence_audit.md]] Where the terms
attach, derivative works must be released under CC-BY-NC-SA-4.0.</p>

<h3>Tian subcortical atlas — citation is the condition</h3>
<p>The Melbourne Subcortex Atlas grants use without restriction <em>subject to the
single condition</em> that any publication using it cites Tian et&nbsp;al. (2020).
It is not a non-commercial licence. The citation below is how that condition is
met.[[note: Verified against the vendored licence text at
<code>assets/src/tian_subcortex/license.txt</code>, not against the registry's
summary of it.]]</p>

<h3>Schaefer 2018 — MIT, over GSP terms that name nothing</h3>
<p>The parcellation labels are MIT (CBIG). Underneath sits Genomics Superstruct
Project data “under its own terms”, and those terms are not named. The classifier
resolves this to <strong>unknown</strong> rather than to MIT, and it is shown here
as unresolved.</p>

<h2>Unsettled, and deliberately not answered</h2>

<p>Whether a model trained on CC-BY-NC-SA data is a derivative work of that data
is recorded in the release manifest as
<code>{e(DOWNSTREAM_REACH_QUESTION.get('status', 'unsettled'))}</code>.
This site does not assert an answer. The conservative reading — assume it does —
is the one that fails safe.[[src: scwbd/release/manifest.py]]</p>

<div class="todo">
<span class="todo-label">Jacob — decision required</span>
<p><strong>The repository has no LICENSE file, and <code>pyproject.toml</code>
declares <code>license = {{ text = "Proprietary" }}</code>.</strong> If any
released artifact inherits CC-BY-NC-SA-4.0, ShareAlike requires derivatives be
released under that same licence, and “Proprietary” is not compatible with it.
This needs a human decision before anything is published, and it is a legal
question rather than an engineering one.</p>
<p>Also needed here: whether SC-WBD is being offered commercially, since that
determines whether the NonCommercial term is a live constraint or a moot one.</p>
</div>

<h2>Owner licence decision, on the record</h2>

<p>The manifest carries the owner's decision <em>and its history</em>, because a
superseded decision is evidence about how the current one was reached.[[src: scwbd/release/manifest.py]]
The current decision accepts attribution; it records that the strongest
supportable claim is <em>“no established restriction remains”</em> and explicitly
<strong>not</strong> <em>“commercially clear”</em>.</p>
""")

    parts.append("<h2>Dataset sources</h2>")
    parts.append(
        f"<p>{len(ds_block.entries)} cards in <code>scwbd/sources/cards/</code>. "
        "Citations are reproduced verbatim; for the ODC-By datasets, attribution is "
        "the whole of the obligation.</p>"
    )
    parts.append('<div class="tablewrap"><table><thead><tr>'
                 "<th>Key</th><th>Citation</th><th>Licence</th></tr></thead><tbody>")
    parts.append(entry_rows(ds_block, "dataset"))
    parts.append("</tbody></table></div>")

    parts.append("<h2>Anatomy and atlas sources</h2>")
    parts.append(
        f"<p>{len(an_block.entries)} entries in <code>scwbd/anatomy/sources.py</code>.</p>"
    )
    parts.append('<div class="tablewrap"><table><thead><tr>'
                 "<th>Key</th><th>Citation</th><th>Licence</th></tr></thead><tbody>")
    parts.append(entry_rows(an_block, "anatomy"))
    parts.append("</tbody></table></div>")

    if unattributable:
        parts.append("<h2>Unattributable inputs</h2>")
        parts.append(
            "<p>These sources could not be rendered into a complete citation. They are "
            "listed rather than dropped, because a missing row is indistinguishable "
            "from a clean one.</p><ul>"
        )
        for key, why in unattributable:
            parts.append(f"<li><code>{e(key)}</code> — {e(why)}</li>")
        parts.append("</ul>")

    parts.append("""
<h2>Redistribution</h2>
<p>Several datasets carry <code>redistribution_class: none</code> — among them
HCP Young Adult, ADNI, UK Biobank and TUH-EEG. <strong>This site hosts no copy of
any of them and links to no derived data.</strong> Access goes through each
provider's own agreement.</p>

</div>
""")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")
    print(f"  datasets: {len(ds_block.entries)}  anatomy: {len(an_block.entries)}"
          f"  unattributable: {len(unattributable)}")
    print(f"  union: {summary[:100]}")


if __name__ == "__main__":
    main()
