#!/usr/bin/env python3
"""Generate notes/INDEX.md from the notes' own frontmatter.

Stdlib only, like site/build.py, and for the same reason: nothing should stand between a note and
the index except this file.

The index is GENERATED so that it cannot drift. A hand-kept index is a second place to be wrong, and
this repository has already paid that twice -- CLAUDE.md records that append-only edits to
`reports/known_issues.md` produced a stale `Status:` line twice and a duplicated heading once. An
entry here exists if and only if a file backs it.

Usage:
    python3 scripts/notes_index.py            # write notes/INDEX.md
    python3 scripts/notes_index.py --check    # exit 1 if it is stale or a link dangles
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTES = ROOT / "notes"
INDEX = NOTES / "INDEX.md"
DIRS = ("decisions", "findings", "questions")

#: status values each directory is allowed to use. A typo becomes an error rather than a new
#: category with one member -- the failure mode that makes "status" stop meaning anything.
VOCAB = {
    "decisions": {"active", "superseded", "reversed"},
    "findings": {"provisional", "measured", "refuted", "superseded"},
    "questions": {"idea", "open", "answered", "rejected"},
}

FM = re.compile(r"\A---\n(.*?)\n---\n", re.S)
H1 = re.compile(r"^#\s+(.+)$", re.M)
LINK = re.compile(r"\[\[([^\]]+)\]\]")


class NoteError(Exception):
    pass


def parse(path: Path) -> dict:
    text = path.read_text()
    m = FM.search(text)
    if not m:
        raise NoteError(f"{path.relative_to(ROOT)}: no frontmatter block")
    meta: dict = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise NoteError(f"{path.relative_to(ROOT)}: frontmatter line without a key: {line!r}")
        key, _, val = line.partition(":")
        val = val.strip().strip('"')
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            meta[key.strip()] = [v.strip() for v in inner.split(",") if v.strip()]
        else:
            meta[key.strip()] = val
    heading = H1.search(text)
    meta.setdefault("title", heading.group(1).strip() if heading else path.stem)
    meta["_slug"] = path.stem
    meta["_path"] = path
    return meta


def collect() -> tuple[dict[str, list[dict]], list[str]]:
    notes: dict[str, list[dict]] = {}
    problems: list[str] = []
    slugs: set[str] = set()
    for d in DIRS:
        got = []
        for p in sorted((NOTES / d).glob("*.md")):
            if p.name == "README.md":
                continue
            try:
                meta = parse(p)
            except NoteError as exc:
                problems.append(str(exc))
                continue
            status = meta.get("status")
            if status not in VOCAB[d]:
                problems.append(
                    f"notes/{d}/{p.name}: status {status!r} is not one of "
                    f"{sorted(VOCAB[d])} -- see notes/{d}/README.md"
                )
            slugs.add(meta["_slug"])
            got.append(meta)
        notes[d] = got

    # `related:` must point at a note that exists. A dangling cross-link is how an index starts
    # describing a tree that is not there.
    for d in DIRS:
        for meta in notes[d]:
            for rel in meta.get("related", []) or []:
                if rel not in slugs:
                    problems.append(
                        f"notes/{d}/{meta['_slug']}.md: related: {rel} does not exist"
                    )
    return notes, problems


def render(notes: dict[str, list[dict]]) -> str:
    total = sum(len(v) for v in notes.values())
    blocked = [m for d in DIRS for m in notes[d] if m.get("blocked_on")]
    live_dec = [m for m in notes["decisions"] if m.get("status") == "active"]
    standing = [m for m in notes["findings"] if m.get("status") in ("measured", "provisional")]
    open_q = [m for m in notes["questions"] if m.get("status") in ("idea", "open")]

    out = [
        "# notes/ INDEX — what is known, what was decided, what is still open",
        "",
        "**This file is GENERATED by `scripts/notes_index.py`. Do not hand-edit it** — write the",
        "note, then run `make notes-index`. Everything below is derived from the notes' own",
        "frontmatter, so an entry exists here if and only if a file backs it. `make notes-check`",
        "fails when this file is stale, a status is off-vocabulary, or a cross-link dangles.",
        "",
        "Read this after `scratch/<TASK>.md` and before starting: it is the two-minute answer to",
        '"has someone already decided this, measured this, or got stuck on this?"',
        "",
        "<!-- BEGIN GENERATED -->",
        "",
        f"**{total} notes** · {len(blocked)} blocked · {len(live_dec)} live decisions · "
        f"{len(standing)} standing findings · {len(open_q)} open questions",
        "",
    ]

    if blocked:
        out += ["### Blocked — needs a decision or an external unblock", ""]
        for m in blocked:
            d = m["_path"].parent.name
            out.append(
                f"- [{m['title']}]({d}/{m['_slug']}.md)"
                + (f" · `{m['task']}`" if m.get("task") else "")
                + f"<br>**Unblock:** {m['blocked_on']}"
            )
        out.append("")

    sections = [
        ("Live decisions", "decisions", lambda m: m.get("status") == "active"),
        ("Standing findings", "findings", lambda m: m.get("status") in ("measured", "provisional")),
        ("Open questions and ideas", "questions", lambda m: m.get("status") in ("idea", "open")),
        ("Superseded, reversed, refuted, answered and rejected", None, None),
    ]
    for title, d, pred in sections[:-1]:
        rows = [m for m in notes[d] if pred(m)]
        if not rows:
            continue
        out += [f"### {title}", ""]
        for m in sorted(rows, key=lambda m: m["_slug"], reverse=True):
            line = f"- [{m['title']}]({d}/{m['_slug']}.md) — `{m['status']}`"
            if m.get("task"):
                line += f" · `{m['task']}`"
            out.append(line)
        out.append("")

    closed = [
        (d, m)
        for d in DIRS
        for m in notes[d]
        if m.get("status") in ("superseded", "reversed", "refuted", "answered", "rejected")
    ]
    if closed:
        out += [f"### {sections[-1][0]}", ""]
        for d, m in sorted(closed, key=lambda x: x[1]["_slug"], reverse=True):
            out.append(f"- [{m['title']}]({d}/{m['_slug']}.md) — `{m['status']}`")
        out.append("")

    out += ["<!-- END GENERATED -->", ""]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if stale or invalid, write nothing")
    args = ap.parse_args()

    notes, problems = collect()
    if problems:
        print("notes are invalid:", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 1

    fresh = render(notes)
    if args.check:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != fresh:
            print(
                "notes/INDEX.md is stale. Run: make notes-index",
                file=sys.stderr,
            )
            return 1
        print(f"notes/INDEX.md is current ({sum(len(v) for v in notes.values())} notes)")
        return 0

    INDEX.write_text(fresh)
    print(f"wrote {INDEX.relative_to(ROOT)} ({sum(len(v) for v in notes.values())} notes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
