"""EEG observation head: source current -> sensor volts on the amplifier clock.

Thesis anchors
--------------
* thesis_contract.tex Sec. 0.3 (T2) --- ``y_E[k] = L(l) x(k dt_E) + eps_E[k]``,
  ``dt_E = 1 ms``.  :meth:`EEGObservationOperator.linear_gaussian` returns
  exactly this pair ``(L, R)`` so the identifiability laboratory consumes the
  same operator the simulator uses.
* body.tex Sec. 7.1 --- "EEG samples need not be downsampled to the fMRI
  repetition time".  :meth:`EEGObservationOperator.observe` reads the latent on
  the *EEG* clock by selection, never by interpolation, and never learns that a
  BOLD head exists.
* body.tex Table ``tab:modalities`` --- EEG dominant bias/variance terms:
  contact location, impedance, conductivity, reference, artifacts,
  coregistration, source non-identifiability.  Every one has a named entry in
  the returned ledger.

Units are volts, always.  The lead field carries V/(A*m); source amplitudes are
current dipole moments in A*m (or A*m/parcel for a parcel-level state).
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field, replace
from typing import Any, Literal, Mapping, Sequence

import torch

from .base import (
    AMPERE_METER,
    DIMENSIONLESS,
    UNKNOWN,
    VOLT,
    BiasTerm,
    ObservationOperator,
    ObservationRead,
    ObservationRefusal,
    Prior,
    Provenance,
    Support,
    TemporalSupport,
    UncertaintyLedger,
    Unresolved,
    VarianceDecomposition,
)
from .leadfield import (
    ElectrodeImpedance,
    ElectrodePositionUncertainty,
    LeadField,
    ReferenceOperator,
    SphericalHeadModel,
)

__all__ = [
    "EEGNoiseModel",
    "ArtifactModel",
    "EEGObservationOperator",
    "pink_noise",
]


# --------------------------------------------------------------------------
# noise
# --------------------------------------------------------------------------


def pink_noise(
    shape: Sequence[int],
    dt: float,
    exponent: float = 1.0,
    *,
    seed: int,
    f_knee: float = 0.5,
    device: torch.device | str = "cpu",
    dtype: torch.dtype = torch.float64,
) -> torch.Tensor:
    """Unit-variance ``1/f**exponent`` noise along the last axis.

    Generated by spectral shaping of white noise on the *native* clock:
    ``S(f) ~ 1 / (f**2 + f_knee**2)**(exponent/2)``, which is finite at DC and
    therefore does not manufacture an unbounded drift out of a finite record.
    """
    shape = tuple(shape)
    n = shape[-1]
    g = torch.Generator(device="cpu").manual_seed(int(seed))
    w = torch.randn(shape, generator=g, dtype=torch.float64)
    W = torch.fft.rfft(w, dim=-1)
    f = torch.fft.rfftfreq(n, d=dt).to(torch.float64)
    shaping = (f**2 + f_knee**2) ** (-exponent / 2.0)
    out = torch.fft.irfft(W * shaping, n=n, dim=-1)
    sd = out.std(dim=-1, keepdim=True).clamp_min(1e-30)
    return (out / sd).to(device=device, dtype=dtype)


@dataclass(frozen=True)
class EEGNoiseModel:
    """Instrument + biological background noise, in volts.

    The three terms are physically distinct and stay separate in the ledger:

    ``background_source_am``
        RMS current dipole moment (A*m) of spatially white, temporally ``1/f``
        background brain activity.  Passed **through the lead field**, so the
        resulting sensor noise is spatially coloured exactly as real EEG
        background is -- not an isotropic white blob bolted onto the sensors.
    ``sensor_white_v``
        Amplifier + electrode thermal noise, per channel, in V/sqrt(Hz).
    ``line_v``
        Mains pickup amplitude in V, scaled per channel by impedance imbalance.
    """

    background_source_am: float = 5e-9
    background_exponent: float = 1.0
    sensor_white_v_per_rthz: float = 30e-9
    line_v: float = 2e-6
    line_hz: float = 60.0
    line_harmonics: int = 3
    line_amplitude_jitter: float = 0.05

    def sensor_white_variance(self, dt: float) -> float:
        """Variance in V**2 for a sample at rate ``1/dt`` (Nyquist bandwidth)."""
        bw = 0.5 / dt
        return (self.sensor_white_v_per_rthz**2) * bw


@dataclass(frozen=True)
class ArtifactModel:
    """Ocular and muscular artifacts as explicit generative processes.

    Artifacts are *not* nuisance to be silently regressed out: they are part of
    ``O_m`` and their removal is a modelling step with its own residual bias.
    """

    blink_rate_hz: float = 0.25
    blink_amplitude_v: float = 100e-6
    blink_width_s: float = 0.20
    saccade_rate_hz: float = 2.0
    saccade_amplitude_v: float = 20e-6
    muscle_amplitude_v: float = 5e-6
    muscle_band_hz: tuple[float, float] = (20.0, 200.0)
    residual_after_cleaning: float = 0.10
    """Fraction of artifact variance surviving ICA/regression cleaning.

    This is the number that makes artifact removal auditable; it enters the
    ledger as an externally bounded bias, not as zero.
    """

    def ocular_topography(self, sensor_pos: torch.Tensor) -> torch.Tensor:
        """Frontal-maximum topography from an anterior-superior eye-field dipole.

        A cornea-retinal dipole sits *outside* the brain compartment, so it is
        modelled by its scalp topography rather than by pushing it through a
        head model that would refuse it (see
        :class:`~scwbd.observe.leadfield.SphericalHeadModel.potential`).
        """
        p = sensor_pos.to(torch.float64)
        c = p.mean(0)
        rel = p - c
        r = rel.norm(dim=-1).clamp_min(1e-9)
        # anterior (+y in RAS-like frames) and inferior weighting
        w = (rel[:, 1] / r).clamp_min(0.0) ** 2 * torch.exp(
            -((rel[:, 2] / r).clamp_min(0.0)) * 2.0
        )
        return w / w.abs().max().clamp_min(1e-12)

    def muscle_topography(self, sensor_pos: torch.Tensor) -> torch.Tensor:
        """Temporalis / neck maximum: lateral and inferior electrodes."""
        p = sensor_pos.to(torch.float64)
        c = p.mean(0)
        rel = p - c
        r = rel.norm(dim=-1).clamp_min(1e-9)
        lateral = (rel[:, 0] / r).abs()
        inferior = (-rel[:, 2] / r).clamp_min(0.0)
        w = lateral * (0.3 + inferior)
        return w / w.abs().max().clamp_min(1e-12)


# --------------------------------------------------------------------------
# the operator
# --------------------------------------------------------------------------


class EEGObservationOperator(ObservationOperator):
    """``O_EEG``: source current dipole moments -> scalp volts at native ms rate.

    Parameters
    ----------
    lead_field
        A :class:`~scwbd.observe.leadfield.LeadField`.  Its ``as_psf()`` becomes
        the spatial support of every returned read, which is the operational
        content of thesis Sec. 2.8.
    dt
        Native amplifier period in seconds (default 1 ms = T2's ``Delta_E``).
    reference, impedance, noise, artifacts
        Instrument nuisance.  All optional; all reported in the ledger when
        present and reported as *unknown* when absent, never as zero.
    """

    name = "eeg_observation_operator"
    version = "0.1.0"

    def __init__(
        self,
        lead_field: LeadField,
        *,
        dt: float = 1e-3,
        clock: str = "eeg_amp",
        reference: ReferenceOperator | None = None,
        impedance: ElectrodeImpedance | None = None,
        noise: EEGNoiseModel | None = None,
        artifacts: ArtifactModel | None = None,
        position_uncertainty: ElectrodePositionUncertainty | None = None,
        head_model: SphericalHeadModel | None = None,
        anti_alias_group_delay: float = 0.0,
        jitter_sd: float = 0.0,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        if lead_field.modality not in ("eeg", "meg"):
            raise ValueError("EEGObservationOperator needs an EEG or MEG lead field")
        self.lead_field = lead_field
        self.reference = reference or ReferenceOperator.infinity(
            lead_field.n_sensors, dtype=dtype
        )
        self.impedance = impedance
        self.noise = noise if noise is not None else EEGNoiseModel()
        self.artifacts = artifacts
        self.position_uncertainty = position_uncertainty
        self.head_model = head_model
        self.dtype = dtype
        self._temporal = TemporalSupport(
            clock=clock,
            dt=float(dt),
            integration_window=0.0,  # EEG is an instantaneous mixture (T2)
            group_delay=float(anti_alias_group_delay),
            jitter_sd=float(jitter_sd),
        )

    # -- descriptors --------------------------------------------------------
    @property
    def support(self) -> Support:
        return self.lead_field.as_support()

    @property
    def temporal(self) -> TemporalSupport:
        return self._temporal

    @property
    def units(self) -> str:
        return self.lead_field.sensor_units

    @property
    def nuisance_priors(self) -> dict[str, Prior]:
        psi: dict[str, Prior] = {}
        if self.head_model is not None:
            for nm, p in zip(
                self.head_model.conductivity.layer_names,
                self.head_model.conductivity.priors,
            ):
                psi[f"sigma_{nm}"] = p
        psi["electrode_position_sd"] = Prior(
            "electrode_position_sd",
            "lognormal",
            (math.log(3e-3), 0.4),
            units="m",
            source="digitiser reproducibility studies (Polhemus/photogrammetry)",
        )
        psi["amplifier_gain"] = Prior(
            "amplifier_gain",
            "normal",
            (1.0, 0.005),
            units=DIMENSIONLESS,
            source="manufacturer calibration tolerance",
        )
        return psi

    # -- the exact T2 form --------------------------------------------------
    def linear_gaussian(
        self, *, include_background: bool = True
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Return ``(L, R)`` for ``y_E[k] = L x(k dt_E) + eps_E[k]``.

        This is the *exact* linear-Gaussian special case of T2, not an
        approximation of :meth:`observe`: calling ``observe`` with
        ``artifacts=None``, ``line_v=0`` and Gaussian noise reproduces
        ``N(L x, R)`` sample-for-sample in distribution.
        """
        L = self.reference.apply(self.lead_field.as_matrix().to(torch.float64))
        if self.impedance is not None:
            L = self.impedance.gain.to(torch.float64).unsqueeze(-1) * L
        n = L.shape[0]

        R = torch.zeros((n, n), dtype=torch.float64)
        white = self.noise.sensor_white_variance(self._temporal.dt)
        R += white * torch.eye(n, dtype=torch.float64)
        if self.impedance is not None:
            R += torch.diag(self.impedance.thermal_noise_variance.to(torch.float64))
        if include_background:
            # spatially white source noise of RMS `background_source_am`
            # -> sensor covariance L L^T * sigma_q^2
            sq = self.noise.background_source_am**2
            R = R + sq * (L @ L.T)
        # the reference operator has already been applied to L; apply it to the
        # sensor-side noise too so that R is the covariance of the *referenced*
        # measurement (dropping this is a common and silent bug)
        M = self.reference.matrix
        if M is not None and self.reference.kind != "infinity":
            Md = M.to(torch.float64)
            R = Md @ R @ Md.T
        return L, R

    # -- the read -----------------------------------------------------------
    def observe(
        self,
        source_amplitude: torch.Tensor,
        latent_temporal: TemporalSupport,
        *,
        seed: int,
        n_samples: int | None = None,
        include_artifacts: bool = True,
        include_noise: bool = True,
        source_orientation: torch.Tensor | None = None,
    ) -> ObservationRead | Unresolved:
        """Observe a latent source trajectory on the **EEG** clock.

        Parameters
        ----------
        source_amplitude
            ``(n_sources, n_latent_samples)`` for a fixed-orientation lead field,
            or ``(n_sources, 3, n_latent_samples)`` for free orientation.  Units
            A*m.
        latent_temporal
            The latent's own clock.  It is *not* modified, and the latent is not
            interpolated: :meth:`sample_latent_on_native_clock` selects the
            samples that coincide with EEG sample instants.
        """
        if source_amplitude.dim() == 3:
            if self.lead_field.orientation == "fixed":
                if source_orientation is None:
                    return Unresolved(
                        reason="free-orientation source amplitudes supplied to a "
                        "fixed-orientation lead field without orientations",
                        missing=("source_orientation",),
                    )
                source_amplitude = torch.einsum(
                    "skt,sk->st", source_amplitude, source_orientation
                )
            else:
                source_amplitude = source_amplitude.reshape(
                    -1, source_amplitude.shape[-1]
                )

        x, idx = self.sample_latent_on_native_clock(
            source_amplitude.to(torch.float64), latent_temporal, n_samples
        )
        n_t = int(x.shape[-1])
        if n_t == 0:
            return Unresolved(
                reason="latent trajectory does not cover a single EEG sample instant",
                missing=("latent_samples",),
            )

        L, _ = self.linear_gaussian(include_background=False)
        if L.shape[1] != x.shape[0]:
            return Unresolved(
                reason=f"lead field expects {L.shape[1]} source components, "
                f"latent supplies {x.shape[0]}",
                missing=("source_space_alignment",),
            )
        signal = L @ x  # volts

        components: dict[str, torch.Tensor] = {"neural": signal.to(self.dtype)}
        y = signal.clone()
        dt = self._temporal.dt
        n_sens = L.shape[0]

        var_measurement = 0.0
        var_within = 0.0

        if include_noise:
            bg_src = self.noise.background_source_am * pink_noise(
                (L.shape[1], n_t), dt, self.noise.background_exponent, seed=seed + 11
            )
            bg = L @ bg_src
            g = torch.Generator(device="cpu").manual_seed(seed + 12)
            white_sd = math.sqrt(self.noise.sensor_white_variance(dt))
            white = white_sd * torch.randn((n_sens, n_t), generator=g, dtype=torch.float64)
            if self.impedance is not None:
                th = self.impedance.thermal_noise_variance.to(torch.float64).sqrt()
                white = white + th.unsqueeze(-1) * torch.randn(
                    (n_sens, n_t), generator=g, dtype=torch.float64
                )
            line = self._line_noise(n_sens, n_t, dt, seed=seed + 13)
            components["background_1f"] = bg.to(self.dtype)
            components["sensor_white"] = white.to(self.dtype)
            components["line"] = line.to(self.dtype)
            y = y + bg + white + line
            var_measurement = float((white.var(dim=-1) + line.var(dim=-1)).mean())
            var_within = float(bg.var(dim=-1).mean())

        if include_artifacts and self.artifacts is not None:
            oc = self._ocular(n_t, dt, seed=seed + 21)
            mu = self._muscle(n_t, dt, seed=seed + 22)
            components["ocular"] = oc.to(self.dtype)
            components["muscle"] = mu.to(self.dtype)
            y = y + oc + mu
            var_measurement += float((oc.var(dim=-1) + mu.var(dim=-1)).mean())

        # reference is applied last to the *measurement*, matching hardware order
        y = self.reference.apply(y)
        for k in list(components):
            components[k] = self.reference.apply(components[k].to(torch.float64)).to(
                self.dtype
            )

        ledger = self._ledger(
            seed=seed,
            var_measurement=var_measurement,
            var_within=var_within,
            signal=signal,
            n_t=n_t,
        )
        return ObservationRead(
            prediction=y.to(self.dtype),
            units=self.units,
            support=self.support,
            temporal=self._temporal,
            ledger=ledger,
            components=components,
            residual_channels={"latent_sample_index": idx},
        )

    # -- noise/artifact generators -----------------------------------------
    def _line_noise(
        self, n_sens: int, n_t: int, dt: float, *, seed: int
    ) -> torch.Tensor:
        if self.noise.line_v <= 0:
            return torch.zeros((n_sens, n_t), dtype=torch.float64)
        g = torch.Generator(device="cpu").manual_seed(int(seed))
        t = dt * torch.arange(n_t, dtype=torch.float64)
        out = torch.zeros((n_sens, n_t), dtype=torch.float64)
        if self.impedance is not None:
            z = self.impedance.z_electrode.to(torch.float64)
            chan = z / z.mean().clamp_min(1e-12)
        else:
            chan = torch.ones(n_sens, dtype=torch.float64)
        chan = chan * (
            1.0
            + self.noise.line_amplitude_jitter
            * torch.randn(n_sens, generator=g, dtype=torch.float64)
        )
        for h in range(1, self.noise.line_harmonics + 1):
            amp = self.noise.line_v / h
            ph = 2 * math.pi * torch.rand(n_sens, generator=g, dtype=torch.float64)
            out += (amp * chan).unsqueeze(-1) * torch.sin(
                2 * math.pi * self.noise.line_hz * h * t.unsqueeze(0) + ph.unsqueeze(-1)
            )
        return out

    def _events(self, rate_hz: float, n_t: int, dt: float, *, seed: int) -> torch.Tensor:
        g = torch.Generator(device="cpu").manual_seed(int(seed))
        p = rate_hz * dt
        return (torch.rand(n_t, generator=g, dtype=torch.float64) < p).to(torch.float64)

    def _ocular(self, n_t: int, dt: float, *, seed: int) -> torch.Tensor:
        a = self.artifacts
        assert a is not None
        topo = a.ocular_topography(self.lead_field.sensor_positions)
        blinks = self._events(a.blink_rate_hz, n_t, dt, seed=seed)
        w = max(int(round(a.blink_width_s / dt)), 3)
        s = torch.linspace(0.0, 1.0, w, dtype=torch.float64)
        kernel = (s**2) * torch.exp(-4.0 * s)
        kernel = kernel / kernel.abs().max().clamp_min(1e-12)
        blink_wave = torch.nn.functional.conv1d(
            blinks.reshape(1, 1, -1),
            kernel.flip(0).reshape(1, 1, -1),
            padding=w - 1,
        )[0, 0, :n_t]
        sac = self._events(a.saccade_rate_hz, n_t, dt, seed=seed + 1)
        g = torch.Generator(device="cpu").manual_seed(int(seed) + 2)
        sac = sac * torch.randn(n_t, generator=g, dtype=torch.float64)
        sac_wave = torch.cumsum(sac, 0)
        sac_wave = sac_wave - sac_wave.mean()
        sac_wave = sac_wave / sac_wave.abs().max().clamp_min(1e-12)
        return topo.unsqueeze(-1) * (
            a.blink_amplitude_v * blink_wave.unsqueeze(0)
            + a.saccade_amplitude_v * sac_wave.unsqueeze(0)
        )

    def _muscle(self, n_t: int, dt: float, *, seed: int) -> torch.Tensor:
        a = self.artifacts
        assert a is not None
        topo = a.muscle_topography(self.lead_field.sensor_positions)
        g = torch.Generator(device="cpu").manual_seed(int(seed))
        w = torch.randn((self.lead_field.n_sensors, n_t), generator=g, dtype=torch.float64)
        W = torch.fft.rfft(w, dim=-1)
        f = torch.fft.rfftfreq(n_t, d=dt).to(torch.float64)
        lo, hi = a.muscle_band_hz
        band = ((f >= lo) & (f <= min(hi, 0.5 / dt))).to(torch.float64)
        out = torch.fft.irfft(W * band, n=n_t, dim=-1)
        sd = out.std(dim=-1, keepdim=True).clamp_min(1e-30)
        return topo.unsqueeze(-1) * a.muscle_amplitude_v * (out / sd)

    # -- ledger -------------------------------------------------------------
    def _ledger(
        self,
        *,
        seed: int,
        var_measurement: float,
        var_within: float,
        signal: torch.Tensor,
        n_t: int,
    ) -> UncertaintyLedger:
        scale = float(signal.abs().max()) if signal.numel() else 0.0

        bias: list[BiasTerm] = [self.reference.bias_term()]

        if self.lead_field.ledger is not None:
            for b in self.lead_field.ledger.bias:
                if b.units == DIMENSIONLESS and scale > 0:
                    bias.append(
                        replace(
                            b,
                            name=f"leadfield.{b.name}",
                            interval=(b.interval[0] * scale, b.interval[1] * scale),
                            units=VOLT,
                        )
                    )
                else:
                    bias.append(replace(b, name=f"leadfield.{b.name}"))

        if self.impedance is not None:
            ib = self.impedance.imbalance_bias()
            bias.append(
                replace(
                    ib,
                    interval=(ib.interval[0] * scale, ib.interval[1] * scale),
                    units=VOLT,
                )
            )

        if self.artifacts is not None:
            r = self.artifacts.residual_after_cleaning
            amp = self.artifacts.blink_amplitude_v
            bias.append(
                BiasTerm(
                    name="artifact_cleaning_residual",
                    interval=(-r * amp, r * amp),
                    status="externally_bounded",
                    units=VOLT,
                    external_bound="artifact-injection recovery on the same "
                    "montage: inject a known ocular/muscular template, run the "
                    "cleaning pipeline, measure the surviving amplitude "
                    "(appendix tab:appendix-calibration-sources, TMS-EEG/artifact "
                    "phantom row)",
                )
            )

        var_param: float | str = UNKNOWN
        if self.position_uncertainty is not None and self.head_model is not None:
            bias.append(self.position_uncertainty.bias_term())

        variance = VarianceDecomposition(
            measurement=var_measurement,
            within_session=var_within,
            between_session=UNKNOWN,
            parameter_posterior=var_param,
            model_class=UNKNOWN,
            numerical=0.0,
            units="V^2",
        )
        return UncertaintyLedger(
            variance=variance,
            bias=tuple(bias),
            model_discrepancy=UNKNOWN,
            model_discrepancy_flag=True,
            validity_domain={
                "units": VOLT,
                "clock": self._temporal.clock,
                "dt_s": self._temporal.dt,
                "bandwidth_hz": (0.0, 0.5 / self._temporal.dt),
                "n_samples": n_t,
                "reference": self.reference.kind,
                "head_model": self.lead_field.meta.get("head_model", "unknown"),
                "source_space_frame": self.lead_field.frame,
                "claim_boundary": "sensor-space voltage prediction; no source "
                "localisation is claimed by this read",
            },
            provenance=Provenance(
                operator=self.name,
                version=self.version,
                frames=(self.lead_field.frame,),
                clocks=(self._temporal.clock,),
                inputs=("source_amplitude[A*m]",),
                references=(
                    "thesis_contract.tex T2",
                    "body.tex tab:modalities (EEG/MEG row)",
                ),
                seed=seed,
            ),
            notes=(
                "between_session variance is 'unknown' rather than 0: a single "
                "session cannot estimate it (thesis Sec. 0.4).",
                "model_class variance is 'unknown' until at least two head "
                "models have been run on this montage.",
            ),
        )

    # -- position-uncertainty propagation ----------------------------------
    def sensor_variance_from_electrode_positions(
        self, source_moment: torch.Tensor
    ) -> torch.Tensor:
        """``Sigma_y`` in V**2 induced by electrode-position covariance.

        Requires a :class:`SphericalHeadModel` (the analytic derivative source).
        Cross-electrode terms are retained.
        """
        if self.position_uncertainty is None or self.head_model is None:
            raise ObservationRefusal(
                code="R01",
                message="electrode position uncertainty requested without a "
                "position covariance and an analytic head model",
                remedy="construct the operator with position_uncertainty= and "
                "head_model=, or read the variance as 'unknown'",
            )
        return self.position_uncertainty.sensor_covariance(
            self.head_model,
            self.lead_field.source_positions,
            self.lead_field.sensor_positions,
            source_moment,
        )
